

export const genres = [
    {genre: 'Action', img: 'https://images.saymedia-content.com/.image/t_share/MTc1MTEyNjc3MzMxODM4Nzg4/anime-genre-list.jpg'},
    {genre: 'Adventure',img: 'https://www.animesoulking.com/wp-content/uploads/2021/01/adventure-anime-740x414.jpg' },
    {genre: 'Cars', img: 'https://wallpaperaccess.com/full/1371822.jpg'},
    {genre: 'Comedy', img: 'https://images.saymedia-content.com/.image/t_share/MTc1MTEwODgwOTYxMjQyMjA3/best-comedy-anime.png'},
    {genre: 'Crime', img: 'https://e1.pxfuel.com/desktop-wallpaper/342/146/desktop-wallpaper-girl-blood-police-anime-murder-art-girl-night-detective-women.jpg'},
    {genre: 'Dementia',img: 'https://wallpaper-house.com/data/out/6/wallpaper2you_107291.jpg' },
    {genre: 'Demons',img: 'https://fictionhorizon.com/wp-content/uploads/2022/10/DemonSlayer.jpg'},
    {genre: 'Drama', img: 'https://miro.medium.com/v2/resize:fit:1400/0*OhsFUyKlB2dfFPoU.jpg'},
    {genre: 'Dub', img: 'https://cdn.technadu.com/wp-content/uploads/2021/05/10-Best-Dubbed-Romance-Anime-Series-1.jpg'},
    {genre: 'Family',img: 'https://wallpaperaccess.com/full/702732.jpg'},
    {genre: 'Fantasy', img: 'https://i.pinimg.com/originals/48/e1/49/48e149fabdf2f5d74da2d71506ab8263.png'},
    {genre: 'Game', img: 'https://static.fandomspot.com/images/02/12092/00-featured-sakamoto-btooom-anime-screenshot.jpg'},
    {genre: 'Harem', img: 'https://japanpowered.com/media/images/rosario_vampire.png'},
    {genre: 'Historica', img: 'https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/11/best-historical-anime-featured-image.jpg'},
    {genre: 'Horror', img: 'https://assets-prd.ignimgs.com/2022/09/27/tokyo-ghoul-1664245107129.jpeg'},
    {genre: 'Josei',img: 'https://honeysanime.com/wp-content/uploads/2015/10/Hakuoki-Shinko-Kaze-no-Tame-Wallpaper-700x394.jpg' },
    {genre: 'Kids',img: 'https://e1.pxfuel.com/desktop-wallpaper/865/419/desktop-wallpaper-anime-series-like-asteroid-in-love-recommend-me-anime.jpg' },
    {genre: 'Magic', img: 'https://cdn.animeukiyo.com/wp-content/uploads/2022/01/best-magic-anime-min-958x575.jpeg'},
    {genre: 'Martial-Arts',img: 'https://i0.wp.com/quotetheanime.com/wp-content/uploads/2019/12/maxresdefault-1024x576.jpg' },
    {genre: 'Mecha',img: 'https://static1.cbrimages.com/wordpress/wp-content/uploads/2023/02/15-best-mecha-anime-ever.jpg'},
    {genre: 'Military', img: 'https://animemotivation.com/wp-content/uploads/2022/08/anime-girl-pointing-gun-wallpaper-military.jpg'},
    {genre: 'Music', img: 'https://honeysanime.com/wp-content/uploads/2018/03/Hibike-Euphonium-crunchyroll-500x281.jpg'},
    {genre: 'Mystery', img: 'https://cdn.myanimelist.net/s/common/uploaded_files/1463851281-e140f1e0423a6bb3e022bf3322323d07.jpeg'},
    {genre:'Parody',img:'https://static.fandomspot.com/images/03/12662/15-watamote-no-matter-how-i-look-at-it-its-you-guys-fault-im-unpopular-anime.jpg'}, 
    {genre:'Police',img:'https://wallpapersmug.com/large/e3b657/game-frost-rainbow-six-siege_.jpg'},
    {genre:'Pyschological',img:'https://static1.cbrimages.com/wordpress/wp-content/uploads/2023/01/the-best-psychological-thriller-anime.jpg'}, 
    {genre:'Romance',img:'https://static.fandomspot.com/images/09/9262/35-kiss-him-not-me-anime-screenshot.jpg'}, 
    {genre:'Samurai',img:'https://wallpaperaccess.com/full/3355.jpg'}, 
    {genre:'School',img:'https://a-static.besthdwallpaper.com/boarding-school-juliet-anime-wallpaper-1280x800-77952_3.jpg'}, 
    {genre:'Sci-fi',img:'https://images.saymedia-content.com/.image/t_share/MTc1MTEyNzg4MTk2ODYxNzY0/best-sci-fi-anime-of-all-time.jpg'},
    {genre:'Seinen',img:'https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/04/seinen-anime-for-action-shonen-fans-1.jpg'}, 
    {genre:'Shoujo',img:'https://www.entoin.com/images/shoujo51.jpg'}, 
    {genre:'Shoujo-ai',img:'https://i0.wp.com/www.animefeminist.com/wp-content/uploads/2017/04/bloomintoyou.jpg?fit=1920%2C1080&ssl=1'}, 
    {genre:'Shounen',img:'https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/03/15-Best-Shonen-Anime-Ever.png'}, 
    {genre:'Slice-of-Life',img:'https://1.bp.blogspot.com/-6EGG_gLqjwc/XSZz8dTroEI/AAAAAAAAAxU/OzzaU-nL2-IhnRT-H1oRwUcHEmrpPE3ywCLcBGAs/s1600/Hyouka.jpg'}, 
    {genre:'Space',img:'https://cdn.myanimelist.net/s/common/uploaded_files/1482904296-3d1605466089635576a773941a47046b.jpeg'},
    {genre:'Sports',img:'https://cdn.animeukiyo.com/wp-content/uploads/2020/05/sports-anime-e1590546237404.jpg'},
    {genre:'Super-Power',img:'https://images.saymedia-content.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:eco%2Cw_1200/MTc0MzgyNDIzMzY5MzI3OTc2/best-super-power-anime.jpg'},
    {genre:'Supernatural',img:'https://api.duniagames.co.id/api/content/upload/file/2517244621611219466.jpg'}, 
    {genre:'Suspence',img:'https://cdn1.clickthecity.com/wp-content/uploads/2022/01/10155704/Psychological-Thriller-Anime.jpg'}, 
    {genre:'Thriller',img:'https://staticg.sportskeeda.com/editor/2022/06/a5774-16561574509370-1920.jpg'}, 
    {genre:'Vampire',img:'https://static1.cbrimages.com/wordpress/wp-content/uploads/2021/10/Vampire-Anime-1.jpg'}, 
    {genre:'Yaoi',img:'https://imgix.ranker.com/list_img_v2/16524/1836524/original/1836524-u5'},
    {genre:'Yuri',img:'https://cdn.animeukiyo.com/wp-content/uploads/2021/11/Citrus.webp'}
    ];
    